# This is a basic workflow to help you get started with Actions

name: BicepInfra-deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Azure Login
        uses: Azure/login@v1.4.2
        with: 
          creds: ${{ secrets.AZURE_SPN_CREDENTIAL }}
      - name: deploy bicepInfra
        working-directory: '${{ github.workspace }}/bicep'
        run: | 
            az deployment group create --what-if -g az-bicep-dev-eus-rg --template-file ./AppServicePlan.bicep
    
  deploy:
    # The type of runner that the job will run on
      runs-on: ubuntu-latest
      needs: [build]
      environment: dev

    # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v3
        - name: Azure Login
          uses: Azure/login@v1.4.2
          with: 
            creds: ${{ secrets.AZURE_SPN_CREDENTIAL }}
        - name: deploy bicepInfra
          working-directory: '${{ github.workspace }}/bicep'
          run: |    
              az deployment group create -g az-bicep-dev-eus-rg --template-file ./AppServicePlan.bicep
